env:
  global:
  - secure: SUEr+rAAMqiMmYyDGWtjbCaRDX6F3wnCQQ0FflTHSwReYxJQzXTNR1GgnhtYQrNNVWw/87W3Mkk/CWioSNsMSYfdrzfIMNjeSom7wgXLL4Ty3df6dLU3iQE8D6H3wfNlMJdZz6Pt+KIvqxJNH9WEI7MuvC/ZQ/Sh4ioCp5k8nM55l4XmFd3/X3jV638qz6wnwNpHfCveD0Ia9/nzXu+FDg98XFw++CaVZ5K3gE8Mzt5De8/4LbtGOJMHRzrkUsNrxmxuGDVoJ/sFyVA2B9oXgCuWF1an7G5DQZHodqy3T56G68g7cdWsR2/GytGuxP7GEUeJf5Qwky5cMkXUNGnKYkw6Mybb5RqeO0g8Lua0kFMApFlbLzlmwDI1CbA+48Y00CrWT/QEij8qMlIbu9Es4iZjdj9fPFZAgca/87IKLCUPErPQY4bFIMAH6Xj5M7NTdSdPnpZs87tdahDjTSomDt5qjeU2GSoF5gUfNldNsyiOsBVzO+KClQv9rfvlvi/46yj5ndeVGSxgK0JC5K71sHhxy1NVXfqCZ4oKPgtaPU2diq6lZEpTTHXED0eIsire/ZXyB3gtQbiKDOkjZst67QGDwSBcQNzdtHt5Yv1do5RCccjnDaniBxquLcNnNRaBCKN6WKhADEpk2wBcyU0/fvDjmtxRgIagdD4jrcNdKAA=
  - secure: Ro2Z6s6JOzAOjVdPoOTxC9ReAYSc6+nyB5oAj1lDUi2/MQ8bEMXU1+FhzFOlE0a8nVAchVZ6dPn8pG7ZQO7aMsHUiKGnv/3/AXlI1Tr5GAMBvA5BtEjAXM4ie3DA7RkGe8hzoBqR+i8gt8ujgNX6e/vJKLLVuU9QHznlZ+L6lZVJUhy3u7bSGGKhsj/Gt8/VFzn6+Qg28vJpumSICmfh4t+LJ40FAB2pdfESGW6RcmVHccu6EEd/2T8MR90i15e8+y+Iqw+HD2DQnQiWUw2aAqGFxj7mcfRiQRhfZFtf477Qg3CeSls4jHhENa69LrgDVZD0kW2/J1/O0CUb6iQPn1poOZ6agJOdfnyOxHk2GXplyjXVNml3D3pxqQUXEdzkI4S2lz8Ki4O0yK3XkdE4n2R2mWpHNBlnSadRfENxUuoOaSmxvL2OvHUO/l1jC2C4T9CjfJmQjDSBiswjydhV08HtaPo/drRBpPs2YTI9O+L00XpjhvTLXVylxJkMjE8TfRhRELNjuBmCT6WnZfTg4remkzkpa/olekn+lO1u2nd0OgpUqevcqCYt77xZXRnVahEdu1vD1jzugt/YWYRvXuMI86arrUTouh3k10Jzg4HVS4OJRNwHdLcYaQA/FC4WIR5zccNHYwKNI9KTmvDapbRAu3cfqOZii9FRT6ApZ1g=
language: java
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- "./gradlew check"
- "./gradlew jacocoTestReport"
after_success:
- bash <(curl -s https://codecov.io/bash)
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: MRu87xv10ga0mSAqDpTma7VtSu/kfCtFxg4bs0DUk5Tmd655ocNUwI78efyOFz2MxN70/o6oQb3X/9krDpYdnEg4RSXr0rCzjJdqs5q4fYpZapAvQ6AcfW4GiZhlWZMXsussCPL7EK3vVP0J20/ejayqbyaMYR+Rjzb8n7Gi90dfWrvK2PwU2rjU5Yk68QPEL3DRLjL6aPoUvqaldjMnv7eY8QxDy7zLRxcG1KP19r0BPcBSqb8q4/GEx7rI9UdcHh1whM4ImYGn7NGRTKVm9KUoEYlrSvZUHKQkIHbFJsSBvxFOVA8NDnhTsNoFaWCLodValWMJjqtEpoMx93cK3LG//EC8gZ+5Q+HVHMyhNOT7Sg7T1Q0/0jDXyeMWNnKTRo0WKLoSExRw8ipjoR32Th4z3FVRgCA4VHCXedFYzFrGSiw/Lh8tx/QkjOobt2pTkjyRWCtFBkqgHTnwvodLtrHju26Dge0+KbDNSQSmg4ac9F++qtKKXkj56RD0lelHLlFDmp+kb+i4Tu99itT7qPqt8izHGau2HGwGE7a/cIGyR1O/yRsIXlruslOsJ8oFJMZmNA5mEV+Mx76i3D2Zq5MENjetF8dCNXoWwTIq5bufxE8ccTnudy8oD/rWJZDqt2Fn7pRzHHXuZpUKQd4xmtWJHD0+PmhIY+7DZbSqUwM=
  app: htwesports
